// File generated by ChatGPT based on Firebase SDK config

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA4KMzCtuafwu5ZooHE9wYH3gEpi1wofs',
    appId: '1:747504777525:web:unknown',
    messagingSenderId: '747504777525',
    projectId: 'germplasmx',
    authDomain: 'germplasmx.firebaseapp.com',
    storageBucket: 'germplasmx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA4KMzCtuafwu5ZooHE9wYH3gEpi1wofs',
    appId: '1:747504777525:android:dcc7a97c1bec15556f747c',
    messagingSenderId: '747504777525',
    projectId: 'germplasmx',
    storageBucket: 'germplasmx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA4KMzCtuafwu5ZooHE9wYH3gEpi1wofs',
    appId: '1:747504777525:ios:dummyappid',
    messagingSenderId: '747504777525',
    projectId: 'germplasmx',
    storageBucket: 'germplasmx.firebasestorage.app',
    iosBundleId: 'com.example.germplasmx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA4KMzCtuafwu5ZooHE9wYH3gEpi1wofs',
    appId: '1:747504777525:macos:dummyappid',
    messagingSenderId: '747504777525',
    projectId: 'germplasmx',
    storageBucket: 'germplasmx.firebasestorage.app',
    iosBundleId: 'com.example.germplasmx',
  );
}